### PR TITLE
Remove Extra Whitespace

### PR DESCRIPTION
**Pull request by bgiesing**
* Remove Trailing Whitespace
* Fix Mixed-Indent

@ianbrunelli

### CODE REVIEW

**Comment by ianbrunelli** [comment]
I'm using tabs for indent. Is there any benefit in using whitespaces?

**Comment by bgiesing** [comment]
This commit fixes some errors that show up when editing in VIM by removing
white spaces.

For example, when you have a file that uses both spaces and tabs, a mixed
indent error shows up because two different kinds of indenting show up
which ruins consistency.

Also, it is recommended to use spaces, see here: http://goo.gl/Za36OV but
in short, tabs can vary in size and spaces always equal the same.

Also a couple of the files had trailing whitespace which is considered bad
practice. See this: http://goo.gl/qqowAm In short, makes diffs harder to
read and a few more things.

**Comment by ianbrunelli** [comment]
Well, the most voted answer in the link you pointed (http://goo.gl/Za36OV) is "Tabs", and I do prefer to use tabs, since it is just one character and I can adjust its size to my taste. But, of couse, this is just a matter of opinion.

Thank you for pointing this issue. I will delete all the trailing whitespaces and change the indetion to use only tabs...

**Comment by bgiesing** [comment]
@ianbrunelli Just updated the commit with tabs instead of spaces and a rebase on the latest commits so it can be automatically merged.

PS2: Replace Spaces with Tabs per-request of Dev and rebase on latest changes.

**Comment by ianbrunelli** [comment]
You're great, @bgiesing! Thank you very much! :smiley:

**Pull request merged**
