### PR TITLE
Changes to make a live demo with gh-pages

### PR DESCRIPTION
**Pull request by mushishi78**

### CODE REVIEW

**Comment by ianbrunelli** [comment]
I'm sorry, but I don't understand exacly what you're doing here. There's already a live demo in http://camporez.github.io. Could you explain it to me?

**Comment by mushishi78** [comment]
Oh okay. I was doing a lot of themes at the same time so I didn't realize that. However, you do have http://camporez.com provided as your homepage link, which is dead.

Beside that,prepending `baseurl` before urls is a common practice because it allows to host on a subdirectory, like with gh-pages. So, these changes are probably worth merging in anyway.

**Comment by ianbrunelli** [comment]
> However, you do have http://camporez.com provided as your homepage link, which is dead.

Sorry, I forgot to change the link on the description (I believe it was changed everywhere else).

> Beside that,prepending baseurl before urls is a common practice because it allows to host on a subdirectory, like with `gh-pages`. So, these changes are probably worth merging in anyway.

Okay. I'll just do some research about `gh-pages` before merging it.

Thanks for the PR. :)

**Comment by mushishi78** [comment]
Here's the jekyll docs: [GitHub Pages - Project Pages](https://jekyllrb.com/docs/github-pages/#project-pages)

**Pull request closed without merging**
